blank_issues_enabled: false
contact_links:
  - name: Start a discussion
    about: ğŸ—¨ Start a friendly conversation with the other members of the community about the samples in this repository.
    url: https://github.com/pnp/powerva-samples/discussions
  - name: Microsoft Tech Community
    url: https://powerusers.microsoft.com/t5/Power-Virtual-Agents-Community/ct-p/PVACommunity
    about: â‰ï¸ Alternatively, submit your technical questions in the Power Virtual Agents Tech Community